Check current branch in release script

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -6,6 +6,13 @@ if [ "$1" != "major" ] && [ "$1" != "minor" ] && [ "$1" != "patch" ]; then
   exit 1
 fi
 
+main_branch=$(git rev-parse --abbrev-ref origin/HEAD | cut -c8-)
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+if [ "$current_branch" != "$main_branch" ]; then
+  echo "Error: not in '$main_branch' branch"
+  exit 1
+fi
+
 cd backend
 version=$(npm version --no-git-tag-version "$1")
 git add package*
